CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    email VARCHAR2(100) UNIQUE,
    contrasena VARCHAR2(100),
    rol VARCHAR2(20) CHECK (rol IN ('cliente', 'admin'))
);

CREATE TABLE habitaciones (
    id_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR2(50),
    precio NUMBER(10,2),
    estado VARCHAR2(20) CHECK (estado IN ('disponible', 'reservada')),
    descripcion VARCHAR2(255)
);

CREATE TABLE reservas (
    id_reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuarios(id_usuario),
    id_habitacion NUMBER REFERENCES habitaciones(id_habitacion),
    fecha_inicio DATE,
    fecha_fin DATE,
    estado VARCHAR2(20) DEFAULT 'pendiente'
);

CREATE TABLE pagos (
    id_pago NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reserva NUMBER REFERENCES reservas(id_reserva),
    monto NUMBER(10,2),
    metodo VARCHAR2(50),
    estado VARCHAR2(20) DEFAULT 'pendiente'
);